Further pinch improvement.

diff --git a/mylibs/bashlib/pinch b/mylibs/bashlib/pinch
--- a/mylibs/bashlib/pinch
+++ b/mylibs/bashlib/pinch
@@ -3,34 +3,62 @@
 # Usage: $ pinch filename start-line end-line
 # By Evan J. Coon
 
-
 FILENAME=$1
 START=$2
 END=$3
 
 ERROR="[PINCH ERROR]"
 
+# Check that the number of arguments is 3
 if [ $# -lt 3 ]; then
     echo "$ERROR Need three arguments: Filename Start-line End-line"
     exit 1
 fi
 
+# Check that the file exists.
 if [ ! -f "$FILENAME" ]; then
     echo -e "$ERROR File does not exist. \n\t$FILENAME"
     exit 1
 fi
 
+# Check that start-line is not greater than end-line
 if [ "$START" -gt "$END" ]; then
     echo -e "$ERROR Start line is greater than End line."
     exit 1
 fi
 
+# Check that start-line is positive.
+if [ "$START" -lt 0 ]; then
+    echo -e "$ERROR Start line is less than 0."
+    exit 1
+fi
+
+# Check that end-line is positive.
+if [ "$END" -lt 0 ]; then
+    echo -e "$ERROR End line is less than 0."
+    exit 1
+fi
+
 NUMOFLINES=$(wc -l < "$FILENAME")
 
+# Check that end-line is not greater than the number of lines in the file.
+if [ "$END" -gt "$NUMOFLINES" ]; then
+    echo -e "$ERROR End line is greater than number of lines in file."
+    exit 1
+fi
+
+# The distance from the end of the file to end-line
 ENDDIFF=$(( NUMOFLINES - END ))
 
+# For larger files, this will run more quickly. If the distance from the
+# end of the file to the end-line is less than the distance from the
+# start of the file to the start-line, then start pinching from the
+# bottom as opposed to the top.
 if [ "$START" -lt "$ENDDIFF" ]; then
     < "$FILENAME" head -n $END | tail -n +$START
 else
     < "$FILENAME" tail -n +$START | head -n $(( END-START+1 ))
 fi
+
+# Success
+exit 0
